sudo: required
services:
    - docker

before_install:
    - docker build -t smartgauravrana/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true smartgauravrana/docker-react npm run test